V2.5.0 dev mcu
mconf/bbb-webrtc-sfu pull request #60
Opened 2019-06-14 17:32 UTC by mariogasparoni

Closes #59

2019-06-24 15:57 UTC, prlanzarin requested changes

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +const OUTPUT_BIT_RATE = 1024;
Add a TODO/FIXME to remember to make this configurable. We have other instances of this (remb, bw configs on element creation) and I'd like to see it straightened in the future.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
That's not quite how errors are supposed to be handled. Please pass every error through the `handleError` (which makes sure errors are uniform). Also look at /kurento/errors.js and constants.js/C.ERRORS for the list of mapped errors. This should be something equal to MEDIA_NOT_FOUND.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
same thing, pass it through the error handler.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
error handler

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
error handler

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +          return await this.destroyHubPort(elementId);
await and then return resolve, otherwise the error might backfire and be unhandled.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/media/media-controller.js
> +              session.connect(mcuSession);
await, otherwise errors might be unhandled

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/media/media-controller.js
> +        return;
there's a ROOM_NOT_FOUND error that could be fired here.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/room.js
> +      throw error;
we should import the utils/handleError method here and use it on the throws. I reckon there wasn't one before, but that's because there shouldn't be any unmapped errors here. Now that there are, we have to use the handler.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/room.js
> +      if (!type || typeof(type) != 'string') {
Why the type validation here? The way I see it it should be validated on user join/media creation and guarantee it's a valid thing for the entirety of the process.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/media.js
> +      throw error;
error handler

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/media.js
> +   * FIXME This method should be definetly be in Kurento adapter.
Open issue to move this to the kurento adapter.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/media-session.js
> +  // FIXME 2: We should move this logic to the adapter,
Open issue to move this to the kurento adapter.

2019-06-24 15:57 UTC, prlanzarin commented on lib/mcs-core/lib/model/media-session.js
> +  // TODO 1: Support hubport for audio medias
Open issue to enhance this, but I think it's a low priority feature.

2019-06-24 16:01 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +const OUTPUT_BIT_RATE = 1024;
https://github.com/mconf/bbb-webrtc-sfu/issues/25
There's an issue for that already. Just comment there that we have one more thing to refactor.
Also, what's up with the output bitrate being 1024?

2019-06-26 16:12 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +const OUTPUT_BIT_RATE = 1024;
We have tested against more than 10+ types of endpoints, 1024kbps is the most "friendly" rate. 
This is a default value, though. This could be changed  for a param, in the future.

2019-06-26 16:12 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
Exceptions should be always threated in a try/catch block.
Besides, in a well designed layered model, this kurento adapter
wouldn't handle things that are'n kurento related, such as "translating
kurento errors messages into an application-specific error". I will change
it now the way you guys do now (specially to avoid breaking your current
error/alert system) but keep in mind that errors could be simply thrown away in the adapter.

2019-06-26 16:12 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Already discussed

2019-06-26 16:12 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Already discussed

2019-06-26 16:12 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Already discussed

2019-06-26 16:13 UTC, mariogasparoni commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +          return await this.destroyHubPort(elementId);
It's correct. But the readability of this function is actually compromised:
that's problably why the error you mentioned was made. In this case
(specially for future functions) i recommend
changing it to async/await pattern and then reviewing the whole code/logic 
of this function. I would leave the refactor of this function for the future
(in a possible maintenance, for example), once this works well now.

2019-06-26 16:13 UTC, mariogasparoni commented on lib/mcs-core/lib/media/media-controller.js
> +              session.connect(mcuSession);
Agreed

2019-06-26 16:13 UTC, mariogasparoni commented on lib/mcs-core/lib/media/media-controller.js
> +        return;
Agreed

2019-06-26 16:14 UTC, mariogasparoni commented on lib/mcs-core/lib/model/media-session.js
> +  // TODO 1: Support hubport for audio medias
Not sure if this should be an issue. I'll let you decide

2019-06-26 16:14 UTC, mariogasparoni commented on lib/mcs-core/lib/model/media-session.js
> +  // FIXME 2: We should move this logic to the adapter,
Same as discussed above

2019-06-26 16:15 UTC, mariogasparoni commented on lib/mcs-core/lib/model/media.js
> +   * FIXME This method should be definetly be in Kurento adapter.
Same as discussed above

2019-06-26 16:15 UTC, mariogasparoni commented on lib/mcs-core/lib/model/media.js
> +      throw error;
Already discussed

2019-06-26 16:15 UTC, mariogasparoni commented on lib/mcs-core/lib/model/room.js
> +    this._mediaSessions = {};
I'll remove it. This is not being used anyways, probably commited by mistake.

2019-06-26 16:16 UTC, mariogasparoni commented on lib/mcs-core/lib/model/room.js
> +      sfuUsers.forEach((_user) => {
No problem in changing to map, but is there any special reason ?

2019-06-26 16:16 UTC, mariogasparoni commented on lib/mcs-core/lib/model/room.js
> +      if (!type || typeof(type) != 'string') {
This method is public and you can't assume it would be called correctly outside.
I opted for not throwing errors in here (due to function simplicity), but 
you could add the error system. I can't see which error should be
send to the end user, though.

2019-06-26 16:17 UTC, mariogasparoni commented on lib/mcs-core/lib/model/room.js
> +      throw error;
I will leave it as it is, once this is working fine.

2019-06-26 20:37 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
I don't agree. Each adapter should format the errors in a single way, otherwise we'll have to add multiple errors handlers throughout the code. The errors should come from the adapter in a format that is recognizable for the rest of the code otherwise it'd too expensive to add new ones. That's why there's a mapping and the mapping works.

If you're worried about losing info, that's why the stack traces are printed in the error handlers. Moreover, that's what the `details` field is used for.

2019-06-26 20:38 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
`Exceptions should be always threated in a try/catch block.` this is not the question here as well. This is a fact, but the `handleError` is a uniformizer rather than a proper handler (and I agree the name might be misleading). It'd still be thrown, but formatted by the uniformizer.

2019-06-26 20:39 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
``` this kurento adapter
wouldn't handle things that are'n kurento related, such as "translating
kurento errors messages into an application-specific error" ``` I also disagree. The adapter are supposed to be interfacing with the rest of the application. Interfacing also means the errors should respect what the interface users expected. Hence why we need the formatting.

2019-06-26 20:41 UTC, prlanzarin commented on lib/mcs-core/lib/model/room.js
> +      if (!type || typeof(type) != 'string') {
`INVALID_OPERATION` or `INVALID_OPERATION` with a `details` object that explains what is wrong and where.

2019-06-26 20:41 UTC, prlanzarin commented on lib/mcs-core/lib/model/media-session.js
> +  // TODO 1: Support hubport for audio medias
It should. Enhancement/feature issue.

2019-06-26 20:43 UTC, prlanzarin commented on lib/mcs-core/lib/model/room.js
> +      sfuUsers.forEach((_user) => {
Just a code quality suggestion, this is not needed. Reason is readability (you wouldn't need to explicitly concat anything), but it's not a blocking thing.

2019-06-26 20:46 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
Also, picture an adapter that is written in a separate application in another language and gives the interface via RPC (e.g.: a clang Janus plugin). Costly to pass unformatted errors via RPC (would need adapter-specific handling in code that isn't supposed to be adapter aware).

2019-06-26 20:52 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +const OUTPUT_BIT_RATE = 1024;
Yeah. Ideally this should match the TIAS/AS fields in the SDPs.

2019-06-26 20:58 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +          return await this.destroyHubPort(elementId);
Ok. The stop method is a mess anyways.
But upon further inspection, having a specific `destroyHubPort` method doesn't make much sense. 
The only reason there's a specific one for the recorder endpoint is that the stop method is different (`stopAndWait`).
The hubport method is the stock one (`release`). So it doesn't need a special case. Also, if I understand correctly, there's an indirection here that is also uneeded. You call destroyHubPort which receives the elementId as a parameter, fetches the hubport, call _destroyHubPort which receives the hub object and then fetch it again (hubPort.id and elementId) are the same, to only then call release.

My suggestion here is just removing those specific methods. The hubport should be released in the remainder of the `stop` method. As ugly as it is, it should work.

2019-06-26 21:14 UTC, prlanzarin commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +          return await this.destroyHubPort(elementId);
https://github.com/mconf/bbb-webrtc-sfu/issues/74

2019-07-10 18:08 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/room.js
> +      throw error;
Reviewed: Room.js is now using the handleError in all functions.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:08 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/media.js
> +      throw error;
Reviewed: Passing by handleError now
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:08 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +          return await this.destroyHubPort(elementId);
Reviewed: await and then return added. 
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:08 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +const OUTPUT_BIT_RATE = 1024;
Reviewed: TODO/FIXME text added.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:09 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw new Error('Could not create new hubport - invalid composite mixer',
Reviewed: All errors are now passing by handleError function. 
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:09 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Reviewed: Passing by handleError function
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:09 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Reviewed: Passing by handleError function
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:09 UTC, RodrigoOkido commented on lib/mcs-core/lib/adapters/kurento/kurento.js
> +      throw error;
Reviewed: Passing by handleError function
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:09 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/room.js
> +      if (!type || typeof(type) != 'string') {
Reviewed: We added a new error in constants.js called ROOM_INVALID_USERS_TYPE. Is being passed in hadleError by parameter in case of error.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:10 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/room.js
> +      sfuUsers.forEach((_user) => {
Reviewed: We decide it to kept in a for each block.  Nothing against to change it if is really necessary.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:10 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/room.js
> +    this._mediaSessions = {};
Reviewed: Attribute removed. Not being used for any purpose.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:11 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/media-session.js
> +  // TODO 1: Support hubport for audio medias
Reviewed: Due to the fact this is low priority and only for enhancements purposes...nothing was modified in this review.
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:11 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/media-session.js
> +  // FIXME 2: We should move this logic to the adapter,
Reviewed: Same as above open issue
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:12 UTC, RodrigoOkido commented on lib/mcs-core/lib/model/media.js
> +   * FIXME This method should be definetly be in Kurento adapter.
Reviewed: Same as above open issue
Check: [#60](https://github.com/mconf/bbb-webrtc-sfu/pull/60/commits/a8e5009ab7a2f9d40df844af24c06e2ecd779a23)

2019-07-10 18:51 UTC, merged

2021-04-25 12:20 UTC, giulio1979 commented
Is this actually functional as for me any attempt to start video results in the regular SFU sessions. How can I check if a user is MCU user ?